# Generated by Django 3.2.9 on 2021-12-04 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantOrders', '0002_auto_20211203_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='CustomerDetail',
            new_name='Customer',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='AmountPaid',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='Discount',
        ),
    ]
