# Generated by Django 3.2.9 on 2021-12-10 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantOrders', '0003_auto_20211203_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('Usertype', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='address',
            name='Line1',
        ),
        migrations.RemoveField(
            model_name='address',
            name='Line2',
        ),
        migrations.RemoveField(
            model_name='address',
            name='ZipCode',
        ),
        migrations.AddField(
            model_name='address',
            name='PostalCode',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='Province',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='line1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='line2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='City',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='Address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Address', to='RestaurantOrders.address'),
        ),
        migrations.AlterField(
            model_name='items',
            name='OrderID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Orders', to='RestaurantOrders.orders'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomerDetails', to='RestaurantOrders.customerdetails'),
        ),
        migrations.CreateModel(
            name='RestaurantMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurantName', models.CharField(max_length=50)),
                ('gstin', models.IntegerField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='RestaurantOrders.address')),
                ('credentails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login', to='RestaurantOrders.credentails')),
            ],
        ),
    ]
